apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - dashboards/hello-goldenpath-idp-dashboard.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: goldenpath-idp

images:
  - name: hello-goldenpath-idp
    newName: hello-goldenpath-idp
    newTag: latest
